// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Connection struct {
	ID       string   `json:"id"`
	Source   *User    `json:"source"`
	Target   *User    `json:"target"`
	Strength *float64 `json:"strength"`
	Type     *string  `json:"type"`
}

type CreateConnectionInput struct {
	SourceID string   `json:"sourceId"`
	TargetID string   `json:"targetId"`
	Strength *float64 `json:"strength"`
	Type     *string  `json:"type"`
}

type CreateUserInput struct {
	Name   string  `json:"name"`
	Avatar *string `json:"avatar"`
}

type UpdateConnectionInput struct {
	Strength *float64 `json:"strength"`
	Type     *string  `json:"type"`
}

type User struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	Avatar      *string       `json:"avatar"`
	Connections []*Connection `json:"connections"`
}
